import React from "react";
import Home from "@/components/Home";
import Head from 'next/head';
import  Navbar  from "../components/Navbar";
import  Footer  from "../components/Footer";
import './global.css';
import { StateContext } from "../context/StateContext";
import { Toaster } from "react-hot-toast";
import 'dotenv/config'

const result = dotenv.config()

if (result.error) {
  throw result.error
}

console.log(result.parsed)
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <StateContext>
      
    <html lang="en">
      <body>
      <div className='layout'>
<Toaster/>
<Head>
  <title>David Leather Website</title>
</Head>
<header>
  <Navbar/>
</header>

<main className='main-container'>
    {children}
</main>

<footer>
    <Footer/>
</footer>

</div>
      </body>
    </html>
    
    </StateContext>
  )
}
