import React from "react";
import Home from "@/components/Home";
import Head from 'next/head';
import  Navbar  from "../components/Navbar";
import  Footer  from "../components/Footer";
import './global.css';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    
    <html lang="en">
      <body>
      <div className='layout'>

<Head>
  <title>David Leather Website</title>
</Head>
<header>
  <Navbar/>
</header>

<main className='main-container'>
    {children}
</main>

<footer>
    <Footer/>
</footer>

</div>
      </body>
    </html>
  )
}
